
#ifndef LOX_INTERPRETER_FUNCTIONTYPE_H
#define LOX_INTERPRETER_FUNCTIONTYPE_H


enum FunctionType {
    FUNCTION_TYPE,
    METHOD_TYPE,
    SCRIPT_TYPE,
    CONSTRUCTOR_TYPE
};


#endif //LOX_INTERPRETER_FUNCTIONTYPE_H
